import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-casestudies',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './casestudies.component.html',
  styleUrl: './casestudies.component.scss',
})
export class CaseStudiesComponent {
  caseStudies = [
    {
      title: 'Plattform für digitale Zusammenarbeit',
      subtitle: 'Wie orchestriert man hochkomplexe Arbeits-Abläufe?',
      metrics: [
        'Zusammenarbeit optimiert',
        'Arbeitsaufwand reduziert',
        'Durchlaufzeiten verkürzt',
        'Nachvollziehbarkeit erhöht',
        'DSGVO-Standards gestärkt',
        'Mobiler Zugriff ermöglicht',
        'Fehlerquoten bei Unterlagen verringert',
      ],
      description: [
        'Viele Verwaltungen und Organisationen kämpfen mit verstreuten Dokumenten, endlosen E-Mail-Schleifen und unklaren Zuständigkeiten. Abläufe werden dadurch langsam vorbereitet, Änderungen erreichen Beteiligte zu spät und Beschlüsse lassen sich nur schwer nachverfolgen. Datenschutz- und Compliance-Anforderungen erhöhen zusätzlich die Komplexität.',
        'Umgesetzt wurde eine Webanwendung, die das komplette Management und die Zusammenarbeit an einem zentralen Ort bündelt – von der Vorbereitung bis zur Nachbereitung. Alle Beteiligten arbeiten in einem einheitlichen Ablauf, Unterlagen bleiben aktuell, und Prozessschritte werden nachvollziehbar gesteuert. Der organisatorische Aufwand sinkt spürbar, weil Abläufe in deutlich kürzerer Zeit durchlaufen werden können. ',
        'Erreicht wurde, dass Unterlagen versioniert, sicher bereitgestellt und mit wenigen Klicks verteilt werden. Änderungen sind sofort für alle ersichtlich; Protokolle, Entscheidungen und Aufgaben bleiben lückenlos dokumentiert. So entsteht Transparenz – von der Einladung bis zur Umsetzung.',
        'Eingebunden wurden intelligente Funktionen, die die tägliche Arbeit spürbar erleichtern: Inhalte lassen sich automatisch ordnen und wiederfinden, Zusammenfassungen unterstützen die Vorbereitung, Hinweise zu Termin- und Fristkonflikten reduzieren Fehler, und die Nachverfolgung von Beschlüssen wird beschleunigt. Die Lösung stärkt zudem Sicherheit, ermöglicht revisionssichere Arbeitsweisen und unterstützt digitale Freigaben – ohne Medienbrüche.',
        'Aus der Perspektive der Beteiligten bedeutet das: weniger Suchzeiten, weniger Doppelarbeit, schnellere Entscheidungen. Abläufe werden besser vorbereitet, Unterlagen sind unterwegs verfügbar, und Verantwortlichkeiten sind klar. Auch mobiles Arbeiten wird unterstützt, sodass Vor- und Nachbereitung flexibel erfolgen kann.',
        'Organisatorisch wurde die Einführung so gestaltet, dass bestehende Systeme weiter genutzt werden können. Prozesse wurden schlank modelliert, Rollen und Rechte klar definiert und Mitarbeitende gezielt befähigt. Dadurch konnte die Plattform zügig produktiv gehen und liefert seitdem messbaren Mehrwert: kürzere Durchlaufzeiten, höhere Qualität in der Entscheidungsfindung und mehr Zufriedenheit bei Mitgliedern sowie Verwaltung.',
        'Die Lösung ist bewusst zukunftsfähig gehalten. Sie lässt sich auf weitere Zentren, Standorte oder Fachbereiche übertragen und modular ausbauen – etwa um öffentliche Informationsportale, automatisierte Berichtswege oder tiefere Integrationen in Dokumentenmanagement und Kollaborationswerkzeuge. So wächst die Plattform mit den Anforderungen, ohne an Komplexität zu gewinnen.',
      ],
    },
    {
      title: 'Analyse-Plattform für Industrieanlagen',
      subtitle:
        'Wie macht man weltweit führende Industrieanlagen noch effizienter?',
      description: [
        'In der Lebensmittelbranche entstehen täglich große Datenmengen aus Anlagen, Sensorik und Qualitätsprüfungen. Häufig liegen Informationen verteilt vor, Auswertungen dauern zu lange und Entscheidungen werden verzögert. Produktions- und Qualitätsverantwortliche wünschen sich einen klaren Blick auf Leistung, Abweichungen und Trends – ohne Medienbrüche, manuelle Exporte oder fehleranfällige Zwischenwege.',
        'Entwickelt wurde für eines der größten Unternehmen der Branche eine Web-Applikation zur Auswertung von Industrieanlagen, aufgesetzt auf einer skalierbaren Enterprise-Frontend-Architektur. Ziel war es, Kennzahlen aus Produktion und Service an einem Ort zusammenzuführen und so Auswertungen zu beschleunigen, Transparenz zu schaffen und die Basis für belastbare Entscheidungen zu legen.',
        'Erreicht wurde eine klare, konsistente Oberfläche, die Informationen strukturiert darstellt und sich an den Arbeitsabläufen in Produktion, Qualität und Instandhaltung orientiert. Daten werden zuverlässig zusammengeführt, Veränderungen sind schnell erkennbar, und die Nachverfolgung von Maßnahmen wird vereinfacht. Dadurch sinken Such- und Abstimmungsaufwände spürbar, während Reaktionszeiten auf Auffälligkeiten kürzer werden.',
        'Eingebunden wurden intelligente Auswertungen, die Muster, Abweichungen und Störquellen frühzeitig sichtbar machen. Zusammenfassungen unterstützen die tägliche Planung, Hinweise auf Schwankungen erleichtern Ursachenanalysen, und wiederkehrende Prüfungen werden standardisiert. So werden Qualitäts- und Effizienzpotenziale gehoben, ohne die Teams mit zusätzlicher Komplexität zu belasten.',
        'Aus Sicht der Anwender bedeutet das: weniger manuelle Arbeit, weniger doppelte Datenpflege und schnellerer Zugang zu den relevanten Kennzahlen. Entscheidungen können auf Basis aktueller Informationen getroffen werden; Berichte, Audits und Abstimmungen lassen sich zügiger vorbereiten. Mobiles Arbeiten wird unterstützt, sodass Schicht- und Serviceteams vor Ort jederzeit Einblick erhalten.',
        'Organisatorisch wurde die Einführung so gestaltet, dass bestehende Systeme weiter genutzt werden können. Schnittstellen wurden pragmatisch angebunden, Rollen und Zugriffe klar geregelt und die Mitarbeitenden gezielt befähigt. Durch die modulare Architektur können Teams unabhängig arbeiten, Releases schneller erfolgen und neue Anforderungen ohne großen Umbau ergänzt werden.',
        'Die Lösung ist zukunftsfähig angelegt: weitere Linien und Standorte lassen sich anschließen, zusätzliche Datenquellen integrieren und neue Auswertungen schrittweise ausrollen. Perspektivisch eröffnet die Plattform Potenziale für vorausschauende Wartung, automatisierte Berichte für Management und Kunden sowie für transparente Nachhaltigkeitskennzahlen – mit messbarem Einfluss auf Kosten, Qualität und Liefertreue.',
      ],
      metrics: [
        'Durchlaufzeiten für Auswertungen verkürzt',
        'Stillstandszeiten und Ausschuss reduziert',
        'Transparenz über Anlagenleistung erhöht',
        'Onboarding und Schulungsaufwand verringert',
        'Release-Zyklen beschleunigt',
        'Wartungs- und Betriebskosten gesenkt',
        'Fehlerquoten in Berichten reduziert',
        'Skalierbarkeit und Erweiterbarkeit gestärkt',
        'Compliance- und Auditfähigkeit verbessert',
        'Nutzungsgrad vorhandener Daten erhöht',
      ],
    },
    {
      title: 'Modernisierung im Retourenmanagement',
      subtitle:
        'Wie kann man die Verarbeitung von 100.000 Retouren pro Tag optimieren?',
      metrics: [
        'Durchsatz erhöht',
        'Bearbeitungszeiten verkürzt',
        'Fehlerquoten reduziert',
        'Prozesskosten gesenkt',
        'Transparenz gesteigert',
        'Entscheidungsqualität verbessert',
        'Wiederverkaufswert optimiert',
        'Compliance gestärkt',
        'Skalierbarkeit gesichert',
        'Stabilität im Betrieb erhöht',
      ],
      description: [
        'Ausgangspunkt war ein gewachsenes System aus mehreren Anwendungen für die Annahme, Verwaltung, Bewertung und Sortierung von Retouren. Hohe Datenmengen, viele Schnittstellen und manuelle Schritte führten zu Verzögerungen, inkonsistenten Informationen und steigenden Kosten. Mitarbeitende verbrachten viel Zeit mit Nacharbeiten, während Führungskräfte nur verzögert belastbare Zahlen erhielten.',
        'Modernisiert und weiterentwickelt wurde die gesamte Verarbeitungskette – von der Erfassung bis zur Bewertung. Datenflüsse wurden bereinigt und vereinheitlicht, Engpässe beseitigt und Abläufe so gestaltet, dass sie zuverlässig und zügig durchlaufen. Entscheidungsrelevante Informationen stehen deutlich schneller bereit, sodass Prioritäten klar gesetzt und Ressourcen wirksam verteilt werden können.',
        'Erreicht wurde eine spürbare Performance-Steigerung bei sehr hohen Lasten: mehrere hundert Millionen Datensätze werden stabil verarbeitet, bis zu zehntausend Retouren pro Stunde sicher durch das System geschleust. Das führt zu kürzeren Durchlaufzeiten, geringeren Wartezeiten bei Gutschriften und zu sinkenden Stückkosten in der Bearbeitung.',
        'Eingeführt wurden transparente Kriterien für die Bewertung und Sortierung, ergänzt um intelligente Hinweise und automatisierte Plausibilitätsprüfungen. Dadurch verringern sich Fehlentscheidungen, Wiederaufbereitungen werden wirtschaftlicher, und der erzielbare Wert der Waren steigt. Teams können sich stärker auf Ausnahmen und wertschöpfende Tätigkeiten konzentrieren.',
        'Verbessert wurde der tägliche Betrieb durch klarere Verantwortlichkeiten, durchgängige Protokollierung und aussagekräftige Kennzahlen in nahezu Echtzeit. Risiken werden früher sichtbar, Ausfälle schneller behoben, und Planbarkeit im Tagesgeschäft steigt. Datenschutz- und Compliance-Anforderungen werden verlässlich eingehalten.',
        'Zukunftsfähig gestaltet wurde die Lösung durch eine modulare Architektur und saubere Datengrundlagen. So lassen sich weitere Standorte, Partner oder Produktkategorien hinzufügen, ohne die Stabilität zu gefährden. KI-gestützte Prognosen, automatische Priorisierung und dynamische Steuerung der Warenströme können schrittweise ausgebaut werden – mit messbarem Mehrwert und kalkulierbarem Risiko.',
      ],
    },
    {
      title: 'Analyse-Tools für Standorte im Energiesektor',
      subtitle:
        'Wie stellt man Standort-KPIs bei 40 Mrd. Euro Umsatz im Detail dar?',
      description: [
        'Viele Organisationen mit mehreren Standorten kämpfen mit verstreuten Datenquellen, unterschiedlichen KPI-Definitionen und aufwändigen Excel-Prozessen. Entscheidungen verzögern sich, weil Zahlen nicht eindeutig vergleichbar sind und Auffälligkeiten erst spät auffallen.',
        'Umgesetzt wurde eine Lösung zur Auswertung und Validierung großer Datenmengen. Standort-KPIs werden einheitlich abgebildet, Abweichungen sind schneller sichtbar, und Kennzahlen lassen sich bis in relevante Detailebenen herunterbrechen. So entstehen klare Prioritäten für Maßnahmen mit messbarem Effekt.',
        'Erreicht wurde, dass die Datenqualität zuverlässig steigt. Validierungs-Regeln prüfen Vollständigkeit, Plausibilität und Grenzwerte; Ausreißer und Lücken werden markiert, bevor sie in Berichte einfließen. Dadurch wächst das Vertrauen in die Zahlen und die Diskussion verlagert sich von Datenstreit zu wirksamen Entscheidungen.',
        'Für Fachbereiche bedeutet das: eine klare Sicht auf Leistung je Standort, Linie oder Schicht. Ursachen für Abweichungen werden schneller erkannt, Ressourcen gezielter eingesetzt und Stillstände sowie Ausschuss reduziert. Kapazitäten und Budgets können faktenbasiert geplant werden, was direkte wirtschaftliche Effekte ermöglicht.',
        'Organisatorisch wurde die Einführung so gestaltet, dass bestehende Systeme weiter genutzt werden können. Ein gemeinsames KPI-Glossar, klare Verantwortlichkeiten und schlanke Abläufe sorgen dafür, dass Teams übergreifend auf derselben Datengrundlage arbeiten und Doppelarbeit entfällt.',
        'Das Management profitiert von verlässlichen, aktuellen Kennzahlen. Berichte entstehen in Minuten statt Tagen; Nachvollziehbarkeit und Revisionssicherheit werden gestärkt. Datenschutz- und Compliance-Anforderungen bleiben gewahrt, ohne den täglichen Betrieb auszubremsen.',
        'Die Lösung ist zukunftsfähig ausgelegt. Neue Standorte, zusätzliche Datenquellen und weitere KPIs können schrittweise ergänzt werden. Perspektivisch lassen sich Prognosen, Anomalie-Erkennung und Szenario-Analysen integrieren, um Entscheidungen noch vorausschauender zu treffen.',
      ],
      metrics: [
        'Datenvalidierung automatisiert',
        'KPI-Transparenz hergestellt',
        'Standort-übergreifende Vergleichbarkeit',
        'Analysezeiten verkürzt',
        'Arbeitsaufwand reduziert',
        'Fehlerquoten gesenkt',
        'Ursachen schneller erkannt',
        'Reporting beschleunigt',
        'Nachvollziehbarkeit erhöht',
        'Skalierbar ausgebaut',
        'Betriebskosten optimiert',
      ],
    },
    {
      title: 'Interaktive Kartenplattform für Verbindungsdaten',
      subtitle:
        'Wie werden tausende Datenpunkte verständlich – in Echtzeit und sicher?',
      metrics: [
        'Datenqualität erhöht',
        'Transparenz gesteigert',
        'Berichtserstellung beschleunigt',
        'Nutzungsrate erhöht',
      ],
      description: [
        'Ausgangslage war eine stetig wachsende Datenmenge aus unterschiedlichen Quellen. Tabellen, Exporte und E-Mails lieferten zwar Zahlen, aber kaum räumlichen Kontext. Entscheidungen dauerten zu lange, weil Muster, Zusammenhänge und Hotspots nur schwer zu erkennen waren.',
        'Umgesetzt wurde eine interaktive Web-Anwendung, die sehr große Datenmengen auf einer Karte übersichtlich darstellt. Nutzerinnen und Nutzer erhalten einen klaren Blick auf Verteilungen, Entwicklungen und Auffälligkeiten und können Fragen in Sekunden beantworten, statt in stundenlanger Tabellenarbeit zu versinken.',
        'Im Backend wurden Daten mit verarbeitet und mithilfe von Data-Science-Methoden angereichert. Erreicht wurde, dass inkonsistente Einträge bereinigt, Standorte verlässlich zugeordnet und relevante Kennzahlen automatisch berechnet werden. Dadurch steigt die Aussagekraft der Informationen, während doppelte oder fehlerhafte Datensätze deutlich reduziert werden.',
        'Ermöglicht wird, dass operative Teams und Entscheidungsträger dieselbe, stets aktuelle Datenbasis nutzen. Räumliche Muster werden sichtbar, Prioritäten lassen sich objektiv setzen, Maßnahmen gezielter planen. Das Ergebnis: weniger Abstimmungsrunden, weniger Rückfragen, weniger Verzögerungen.',
        'Leistungsengpässe wurden durch sinnvolle Aggregation und effiziente Datenbereitstellung vermieden. Karten reagieren flüssig, auch bei sehr vielen Einträgen. Das steigert die Akzeptanz im Alltag, verkürzt Wartezeiten und erhöht die Nutzung im gesamten Team.',
        'Sicherheit und Datenschutz wurden von Beginn an berücksichtigt. Rollen und Rechte sorgen für klare Zugriffe, sensible Inhalte werden nur dort gezeigt, wo sie wirklich benötigt werden. Prozesse und Speicherkonzepte unterstützen eine DSGVO-konforme Nutzung und schaffen Vertrauen bei allen Beteiligten.',
        'Die Einführung wurde pragmatisch gestaltet: vorhandene Systeme bleiben nutzbar, Schnittstellen binden Datenquellen ohne Brüche an. Schulungsaufwand blieb gering, da die Anwendung intuitiv bedienbar ist. Spürbar sind kürzere Durchlaufzeiten, weniger manuelle Schritte und schnellere, belastbare Reports.',
        'Die Lösung ist zukunftsfähig ausgelegt. Sie lässt sich auf weitere Bereiche, Regionen oder Anwendungsfälle übertragen und modular erweitern – etwa um automatische Benachrichtigungen, Trendprognosen oder zusätzliche Datenquellen. So wächst der Nutzen mit den Anforderungen, ohne an Einfachheit zu verlieren.',
      ],
    },
    {
      title: 'Interaktive Montage- und Berechnungs-Plattform',
      subtitle:
        'Wie kann ich Montageabläufe und Berechnungen in der Automobilindustrie interaktiv darstellen?',
      description: [
        'In vielen Betrieben verursachen uneinheitliche Arbeitsabläufe, verteiltes Wissen und zeitaufwändige Rückfragen vermeidbare Fehler bei der Montage und Inbetriebnahme. Stillstände, Nacharbeiten und unklare Verantwortlichkeiten treiben die Kosten nach oben und bremsen die Produktivität. Schulungen binden zusätzliche Ressourcen, während erfahrene Mitarbeitende schwer zu ersetzen sind.',
        'Umgesetzt wurde eine interaktive Web-Anwendung, die Wissen und Abläufe zentralisiert und Schritt für Schritt sicher durch die Montage führt. Arbeitsweisen wurden vereinheitlicht, Informationssilos aufgelöst und die Dokumentation an einem Ort gebündelt. Dadurch sinken Suchzeiten, Missverständnisse werden reduziert und Freigaben erfolgen nachvollziehbar.',
        'Erreicht wurde eine deutliche Senkung der Fehlerquote, kürzere Rüst- und Durchlaufzeiten sowie mehr Sicherheit in der Ausführung. Entscheidungen lassen sich auf Basis aktueller Informationen schneller treffen, Qualitätsstandards werden konsequent eingehalten und Gewährleistungsrisiken verringert. First-Time-Right steigt, Nacharbeiten und Serviceeinsätze nehmen spürbar ab.',
        'Eingebunden wurden KI-gestützte Unterstützungen, die Inhalte schneller auffindbar machen, wiederkehrende Muster sichtbar werden lassen und Hinweise zur optimalen Vorgehensweise geben. Dadurch wird Wissen nachhaltig gesichert, auch wenn Schlüsselpersonen ausfallen, und neue Mitarbeitende erreichen schneller ein produktives Niveau.',
        'Aus Sicht der Anwender bedeutet das: klare Abläufe statt improvisierter Einzellösungen, weniger Medienbrüche und jederzeit aktuelle Informationen – auch mobil vor Ort. Verantwortlichkeiten werden transparent, Freigaben erfolgen zügiger, und die Arbeit fühlt sich insgesamt ruhiger und kontrollierter an.',
        'Organisatorisch wurde die Einführung so gestaltet, dass bestehende Systeme weiter genutzt werden konnten. Rollen und Rechte wurden eindeutig geregelt, Datenschutzanforderungen konsequent berücksichtigt und die Belegschaft gezielt befähigt. Die Lösung ist modular erweiterbar und kann auf weitere Standorte, Produkte und Märkte übertragen werden – ohne an Komplexität zu gewinnen.',
      ],
      metrics: [
        'Fehlerquote gesenkt',
        'Stillstandzeiten verringert',
        'Schulungsaufwand reduziert',
        'Service- und Garantiekosten gesenkt',
        'Transparenz und Nachvollziehbarkeit erhöht',
        'Wissenssicherung aufgebaut',
      ],
    },
    {
      title: 'Konfigurator für Nutz- und Flottenfahrzeuge',
      subtitle:
        'Wie werden komplexe Transporter- und Baufahrzeug-Varianten verkaufsfähig konfiguriert?',
      metrics: [
        'Angebotserstellung beschleunigt',
        'Fehlerquoten in Angeboten gesenkt',
        'Abschlussquote gesteigert',
        'Erlöse pro Auftrag erhöht',
        'Transparenz und Compliance gestärkt',
        'Einarbeitungszeit im Vertrieb reduziert',
        'Kundenerlebnis verbessert',
      ],
      description: [
        'Viele Anbieter von Transportern und gewerblichen Fahrzeugen standen vor der Herausforderung, dass ihre Modelle nicht in klassischen PKW-Konfiguratoren abbildbar waren. Variantenvielfalt, branchenspezifische Auf- und Ausbauten sowie zahlreiche Abhängigkeiten machten die Angebotserstellung aufwendig. Vertriebsteams arbeiteten mit Tabellen, PDFs und manuellen Rückfragen. Das führte zu langen Durchlaufzeiten, vermeidbaren Fehlern und verpassten Abschlüssen.',
        'Umgesetzt wurde ein spezialisierter Konfigurator, der die Komplexität für den Vertrieb handhabbar macht. Ausstattungen, Aufbauoptionen und betriebliche Anforderungen werden in einen klaren, geführten Ablauf übersetzt, sodass gültige Zusammenstellungen entstehen und Angebote in kurzer Zeit erstellt werden können. Auf diese Weise wird der Entscheidungsweg verkürzt, während Verlässlichkeit und Nachvollziehbarkeit steigen.',
        'Erreicht wurde, dass Klärungsschleifen deutlich seltener nötig sind und Kundinnen und Kunden schneller zu einer passgenauen Fahrzeugkonfiguration gelangen. Der Vertrieb gewinnt Sicherheit in der Beratung, kann Zusatznutzen gezielt anbieten und liefert konsistente Preise sowie Bedingungen. Das steigert Vertrauen, reduziert Reklamationen und erhöht die Wahrscheinlichkeit eines Abschlusses.',
        'Organisatorisch wurde die Einführung so gestaltet, dass bestehende Arbeitsweisen berücksichtigt bleiben: Zuständigkeiten wurden klar definiert, Freigaben und Richtlinien transparent gemacht und die Pflege von Ausstattungs- und Preislogik zentralisiert. Mitarbeitende wurden gezielt geschult, sodass der Nutzen unmittelbar spürbar wurde: weniger Aufwand in der Angebotserstellung, bessere Qualität und mehr Fokus auf Beratung statt Administration.',
        'Die Lösung ist zukunftsfähig angelegt. Sie lässt sich auf weitere Baureihen, Märkte und Partner übertragen und unterstützt eine schrittweise Erweiterung des Angebots. Damit wächst der Konfigurator mit den Anforderungen, ohne an Bedienbarkeit zu verlieren – ein belastbares Fundament für skalierbares Wachstum im gewerblichen Fahrzeuggeschäft.',
      ],
      bullets: [
        'Zusammenarbeit optimiert',
        'Arbeitsaufwand reduziert',
        'Durchlaufzeiten verkürzt',
        'Abschlussquote erhöht',
        'Preis- und Ausstattungslogik vereinheitlicht',
        'Nachvollziehbarkeit und Compliance gestärkt',
        'Onboarding im Vertrieb erleichtert',
        'Skalierung auf weitere Produktlinien vorbereitet',
      ],
    },
    {
      title: 'Intelligente Plattform für Agrarbetriebe',
      subtitle:
        'Wie bringe ich eine der ältesten Industrien ins digitale Zeitalter?',
      description: [
        'Viele Betriebe stehen vor der gleichen Hürde: Informationen liegen verstreut, Entscheidungen werden unter Zeitdruck getroffen, und Nachweise binden wertvolle Stunden. Das führt zu vermeidbaren Kosten, Unsicherheiten in der Planung und unnötigem Administrationsaufwand.',
        'Umgesetzt wurde eine zentrale Web-Lösung, die betriebliche Abläufe, Planung und Dokumentation an einem Ort bündelt. Daten bleiben aktuell, Zuständigkeiten sind klar und Arbeitsschritte lassen sich in einem durchgängigen Ablauf steuern. Doppelerfassungen, Medienbrüche und fehleranfällige Tabellen werden spürbar reduziert.',
        'Entwickelt wurde der Ansatz, Planungen schneller und fundierter vorzubereiten. Änderungen greifen sofort, Abstimmungen verkürzen sich, und saisonale Aufgaben lassen sich mit wenigen Handgriffen wiederverwenden. So entsteht Tempo in der Vorbereitung und Ruhe in der Durchführung.',
        'Eingebunden wurden Auswertungen, die aus betrieblichen Daten konkrete Hinweise ableiten: Wo lohnt sich der Einsatz von Ressourcen, wo lässt sich sparen, und wo entstehen Risiken, wenn nicht gegengesteuert wird. Entscheidungen werden nachvollziehbar, Erträge stabilisiert und der Mitteleinsatz gezielter.',
        'Erreicht wurde eine lückenlose, revisionssichere Dokumentation. Nachweise und Berichte lassen sich ohne Zusatzaufwand erstellen; Termine, Fristen und Vorgaben geraten nicht mehr in Vergessenheit. Das mindert Risiken, stärkt die Compliance und gibt Sicherheit bei Prüfungen.',
        'Aus Sicht des Teams wird die tägliche Arbeit einfacher: weniger Suchen, weniger Rückfragen, klare Aufgaben und mobiler Zugriff im Feld. Aus Sicht der Betriebsführung entsteht Transparenz über Kosten, Fortschritt und Wirkung einzelner Maßnahmen – in einer Sprache, die verständlich ist und auf das Wesentliche fokussiert.',
        'Die Einführung wurde pragmatisch gestaltet: bestehende Arbeitsweisen wurden übernommen, entlastende Automatisierungen schrittweise ergänzt und Mitarbeitende gezielt befähigt. Dadurch ging die Lösung zügig produktiv und lieferte früh messbaren Nutzen – von eingesparter Zeit bis zu besser abgesicherten Entscheidungen.',
        'Zukunftsfähig ausgelegt, lässt sich die Lösung problemlos auf weitere Flächen, Standorte oder Kulturen übertragen und modulartig erweitern – etwa um tiefere Analysen, zusätzliche Berichte oder Integrationen. So wächst die Plattform mit den Anforderungen, ohne an Komplexität zu gewinnen.',
      ],
      metrics: [
        'Dünge-Bedarfsplanung präzisiert',
        'Acker-Verwaltung optimiert',
        'Betriebskosten gesenkt',
        'Erträge stabilisiert',
        'Arbeitsaufwand reduziert',
        'Fehlerquoten verringert',
      ],
    },
    {
      title: 'Ladestations-Finder für Elektromobilität',
      subtitle:
        'Wie finden Nutzer verlässlich eine passende Ladesäule – schnell und ohne Umwege?',
      metrics: [
        'Nutzerzufriedenheit erhöht',
        'Konversion auf der Website gesteigert',
        'Supportanfragen reduziert',
        'Durchlaufzeiten bis zum Ladevorgang verkürzt',
        'Datenqualität verbessert',
        'Mobile Performance optimiert',
        'Reichweite für Standorte erhöht',
        'DSGVO-Standards gestärkt',
      ],
      description: [
        'Viele E-Mobilitätsangebote scheitern nicht an der Technik der Fahrzeuge, sondern an der Suche nach der passenden Lademöglichkeit. Informationen sind verstreut, unvollständig oder veraltet. Nutzende springen ab, wenn Ladepunkte schwer zu finden sind oder die Darstellung auf dem Smartphone hakt. Betreiberinnen und Betreiber verlieren Reichweite und Umsatz, während Supportteams mit vermeidbaren Nachfragen belastet werden.',
        'Entwickelt wurde ein nutzerzentriertes Frontend mit integriertem Ladestations-Finder, das geprüfte Standortdaten aus einem externen Anbieter bündelt. Die Lösung führt Suchende schnell zur passenden Lademöglichkeit, vermeidet Medienbrüche und schafft Vertrauen durch klare, einheitliche Darstellungen. So wird aus der Suche ein reibungsloser Einstieg in den Ladevorgang.',
        'Erreicht wurde, dass Menschen in Sekundenschnelle verlässliche Optionen entdecken – unabhängig davon, ob sie am Desktop planen oder unterwegs handeln. Relevante Informationen werden verständlich priorisiert, Wege werden kürzer, und Abbrüche nehmen spürbar ab. Das Ergebnis: mehr erfolgreiche Ladevorgänge und höhere Zufriedenheit.',
        'Für die Betreiberseite bedeutet die Lösung: bessere Sichtbarkeit der Standorte, höhere Auslastung und planbarere Spitzen. Rückfragen im Support sinken, da Informationen konsistenter und leichter zugänglich sind. Gleichzeitig verbessert sich die Entscheidungsqualität, weil Nutzungsdaten und Rückmeldungen strukturiert ausgewertet werden können.',
        'Wesentlich war die Sicherung der Datenqualität. Zusammengeführt wurden externe Standort- und Metadaten, Plausibilitäten geprüft und Inkonsistenzen reduziert. Aktualisierungen greifen ohne Unterbrechungen, sodass die Darstellung aktuell bleibt. Das stärkt die Verlässlichkeit – eine zentrale Voraussetzung, um Vertrauen aufzubauen.',
        'Großen Einfluss hatte die konsequente Ausrichtung auf Geschwindigkeit und Bedienbarkeit. Seiten laden zügig, Interaktionen reagieren unmittelbar, und die Darstellung bleibt auf kleinen Bildschirmen übersichtlich. Barrierearme Gestaltung unterstützt unterschiedliche Nutzungssituationen und reduziert Fehler. Das wirkt sich direkt auf Konversion und Wiederkehr aus.',
        'Datenschutz und Sicherheit wurden pragmatisch und wirkungsvoll berücksichtigt. Es werden nur notwendige Daten verarbeitet, Transparenz wird gewahrt, und gängige Anforderungen an Einwilligungen und Aufbewahrung werden eingehalten. So entsteht ein Angebot, das überzeugt, ohne zusätzliche Risiken zu schaffen.',
        'Die Lösung ist zukunftsfähig ausgelegt. Sie lässt sich um weitere Regionen, Tarifinformationen oder Reservierungs- und Flottenfunktionen erweitern. Auch ein White-Label-Einsatz ist möglich, um Partnern schnell eine eigene Oberfläche bereitzustellen. Damit wächst die Plattform mit dem Bedarf – ohne an Komplexität zu gewinnen.',
      ],
      implementation: [
        'Nutzerführung vereinfacht',
        'Frontend umgesetzt',
        'Externer Datenanbieter angebunden',
        'Datenqualität gesichert',
        'Mobile-Optimierung durchgeführt',
        'Cross-Browser-Kompatibilität geprüft',
        'UI- und Performance-Tests abgeschlossen',
        'Barrierearme Gestaltung gestärkt',
        'Supportaufwand reduziert',
        'DSGVO-Anforderungen berücksichtigt',
      ],
    },
  ];
}
