import { Routes } from '@angular/router';
import { HomeComponent } from './home/home.component';
import { ImpressumComponent } from './impressum/impressum.component';
import { KontaktComponent } from './kontakt/kontakt.component';
import { AboutComponent } from './about/about.component';
import { CaseStudiesComponent } from './casestudies/casestudies.component';
import { NewsletterComponent } from './newsletter/newsletter.component';
import { ProgrammierungComponent } from './programmierung/programmierung.component';
import { KIComponent } from './kuenstliche-intelligenz/ki.component';
import { BarrierefreiheitComponent } from './barrierefreiheit/barrierefreiheit.component';
import { ApiSchnittstellenComponent } from './api-schnittstellen/api-schnittstellen.component';
import { WebAppsComponent } from './web-apps/web-apps.component';
import { DataScienceComponent } from './data-science/data-science.component';
import { SoftwareArchitektComponent } from './software-architekt/software-architekt.component';

export const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'about', component: AboutComponent },
  { path: 'casestudies', component: CaseStudiesComponent },
  { path: 'programmierung', component: ProgrammierungComponent },
  { path: 'kuenstliche-intelligenz', component: KIComponent },
  { path: 'barrierefreiheit', component: BarrierefreiheitComponent },
  { path: 'data-science', component: DataScienceComponent },
  { path: 'software-architekt', component: SoftwareArchitektComponent },
  { path: 'api-schnittstellen', component: ApiSchnittstellenComponent },
  { path: 'web-apps', component: WebAppsComponent },
  { path: 'newsletter', component: NewsletterComponent },
  { path: 'kontakt', component: KontaktComponent },
  { path: 'impressum', component: ImpressumComponent },
  { path: '**', redirectTo: '' },
];
